[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = false

[tasks.format-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check", "-v"]

[tasks.ci]
dependencies = [
    "format-check",
    "test"
]